from . import description
from . import instagram
from . import locations
from . import OK
from . import consultation
from . import reception
from . import services
from . import telegram
from . import vk
from . import YouTube
